apiVersion: v1
kind: Service
metadata:
  name: service2-svc
spec:
  ports:
    - nodePort: 31918
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: mabutkovic/service2:latest
          ports:
            - containerPort: 8080