apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  ports:
    - nodePort: {{ .Values.port }}
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}
  type: NodePort